login:
    path: /login
    defaults:
        _controller: OCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /advert

app:
    resource: '@AppBundle/Controller/'
    type: annotation
